# Generated by Django 3.2.2 on 2021-05-08 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Advisors', '0002_advisorappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorappointments',
            name='bookingTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
